apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - name: {{ .Values.service.portname }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol | default "TCP" }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
